### ISSUE TITLE
Explicit dependency on mod_forum

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/moodle-message_appcrue#3]
The plugin performs low-level access to `forum` and `forum_discussions` DB tables.

Even when `mod_forum` is the standard plugin, it would be cleaner to declare explicit dependency on it in this case as per https://docs.moodle.org/dev/Communication_Between_Components#General_rules_for_inter-component_communications

See https://docs.moodle.org/dev/version.php for details

**Comment by juacas** [comment]
Thanks! Fixed.
