### ISSUE TITLE
not sending notificacions push since November 3rd, 2022

### ISSUE THREAD

**Issue by jpahullo** [juacas/moodle-message_appcrue#7]
In our institution have found some problem with this plugin. It seems that the implementation of the push message is not fully suit.

Since November 3rd, 2022 (we have found detected this today), our Moodle instance tries to send message without success.

The problem shown in Moodle cron says something like:

```shell
Sending messages to NNNNNNNNNN (MMMMMM) ++ Push API Response:{"errors":{"type":"NotificationNotCreated","message":["Target can not be empty"]}} ++
* line 163 of /message/output/appcrue/message_output_appcrue.php: call to debugging()
* line 105 of /message/output/appcrue/message_output_appcrue.php: call to message_output_appcrue->send_api_message()
* line 509 of /lib/classes/message/manager.php: call to message_output_appcrue->send_message()
* line 388 of /lib/classes/message/manager.php: call to core\message\manager::call_processors()
* line 356 of /lib/classes/message/manager.php: call to core\message\manager::send_message_to_processors()
* line 346 of /lib/messagelib.php: call to core\message\manager::send_message()
* line 369 of /mod/forum/classes/task/send_user_notifications.php: call to message_send()
* line 153 of /mod/forum/classes/task/send_user_notifications.php: call to mod_forum\task\send_user_notifications->send_post()
* line 341 of /lib/cronlib.php: call to mod_forum\task\send_user_notifications->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```

And before sending message, [the piece of code initializes an empty target stdClass](https://github.com/juacas/moodle-message_appcrue/blob/master/message_output_appcrue.php#L144-L147).

Maybe have the protocol requisites changed?

**Comment by jpahullo** [comment]
At https://developers.twinpush.com/developers/api#post-create appears the standard. Beforehand, the code seems correct, but an empty object (with name and values empty) is not accepted.

**Comment by jpahullo** [comment]
Maybe, omitting target_property could work? The examples below that sections, show examples without the `target_property` as working.

**Comment by juacas** [comment]
It seems that the API has recently changed  or something. I'll released a new version that addresses this issue with your suggestion. Thanks.

**Comment by juacas** [comment]
> At https://developers.twinpush.com/developers/api#post-create appears the standard. Beforehand, the code seems correct, but an empty object (with name and values empty) is not accepted.

It's weird because this worked months ago. In fact, it is workig now with empty values from Postman. Nevetheless, I publish a new release without the unneeded elements of the JSON.
